image:
  tag: 0.4.10

persistence:
  size: 10Gi
  storageClass: "faster"


resources : 
  requests:
    cpu: "1.5"
    memory: 2048Mi
  limits:
    memory: 2048Mi
    cpu: "1.5"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: hlf-couchdb
