image:
  tag: 1.4.3

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "cluster-letsencrypt-production"
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - ${CA_URI}
  tls:
    - secretName: ca--tls
      hosts:
        - ${CA_URI}

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

caName: ca

postgresql:
  enabled: true

config:
  hlfToolsVersion: 1.3.0
  csr:
    names:
      c: IE
      st: Dublin
      l:
      o: "AID:Tech"
      ou: Blockchain
  affiliations:
    aidtech: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: hlf-ca
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: postgresql
          release: ca
      topologyKey: "kubernetes.io/hostname"
