apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cluster-letsencrypt-production
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    # TODO: Change email address to yours
    email: paul@flexper.fr
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cluster-letsencrypt-production
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
