---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-peer
  namespace: peers
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - pods
  - pods/log
  verbs:
  - "*"
